name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build_test_publish_job:
    name: Publish job
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up GnuPG
        run: brew install gnupg
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: Upload to Google Play
        run: bundle exec fastlane clean_test_bundle_publish
